### ISSUE TITLE
Noticeable latency when switching between menu items

### ISSUE THREAD

**Issue by ilya-zlobintsev** [pop-os/cosmic-launcher#138]
When switching between items in the menu (with either arrow keys or ctrl+j/k), there is a noticeable latency, probably somewhere around 100-200ms. It feels worse than the old pop-launcher menu in the gnome shell extension.

**Comment by leviport** [comment]
I thought I was seeing this as well, but then I noticed something that might explain what's going on. It looks like the action is performed upon key released, rather than upon key pressed. If I hold down the key, the cursor doesn't move until I let up off the key. Unless I do very quick key presses, this gives me an impression of sluggishness.

**Comment by ilya-zlobintsev** [comment]
You're right, that was the problem
