### ISSUE TITLE
Search result highlights covered up by separator line

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-launcher#78]
The second, fourth, fifth, and seventh search results appear to have a gap in their lower border because the separator line (that goes between results) shows up on top of the highlight.

![Screenshot_2023-12-27_14-03-44](https://github.com/pop-os/cosmic-launcher/assets/7199422/e757e902-3a15-495c-8222-c4b4626f5e24)

The other results aren't quite as bad, but still have a thinner bottom border than all the other sides because the separator partially overlaps.

![Screenshot_2023-12-27_14-04-20](https://github.com/pop-os/cosmic-launcher/assets/7199422/a14567b5-5985-4bbf-ab5c-ca6929175b90)

**Comment by wash2** [comment]
Would the desired behavior be that the outline shows on top of the separator?

**Comment by jacobgkau** [comment]
> Would the desired behavior be that the outline shows on top of the separator?

That's maybe a question for @pop-os/ux, but that does seem like the sane behavior to me.

**Comment by maria-komarova** [comment]
> Would the desired behavior be that the outline shows on top of the separator?

Sounds good to me.

**Comment by WatchMkr** [comment]
The outline around the search box should not move from the text input. This is because the text input always has focus and can be typed in at any time.

The active list item is distinguishable by a highlight that looks to be the same as on-hover for other list items.

https://www.figma.com/file/KjWhHsdjRU8Ih3Ib1m3t7B/Launcher?node-id=17%3A1116&mode=dev

Note, the first item in the Launcher list is always highlighted so the user knows pressing enter will activate that item.
