### ISSUE TITLE
`nix build` fails with error message

### ISSUE THREAD

**Issue by Mastermindaxe** [pop-os/cosmic-launcher#87]
Hey everyone :wave: Nix build fails with the following message:
```
cosmic-launcher on  master is 📦 v0.1.0 via 🦀 
❯ nix build
warning: ignoring untrusted substituter 'https://nix-community.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
error: builder for '/nix/store/gjd7kvv35iypazl7z3vk4a7f3ib2wspj-cosmic-launcher-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       > will append /build/source/.cargo-home/config.toml with contents of /nix/store/kjjjn9jnmqpcg9ds45jj5a5ix84qsdi8-vendor-cargo-deps/config.toml
       > default configurePhase, nothing to do
       > building
       > ++ command cargo --version
       > cargo 1.70.0 (ec8a8a0ca 2023-04-25)
       > ++ command cargo check --release --all-targets
       > error: package `libcosmic v0.1.0 (https://github.com/pop-os/libcosmic/#bf050881)` cannot be built because it requires rustc 1.71 or newer, while the currently active rustc version is 1.70.0
       > Either upgrade to rustc 1.71 or newer, or use
       > cargo update -p libcosmic@0.1.0 --precise ver
       > where `ver` is the latest version of `libcosmic` supporting rustc 1.70.0
       For full logs, run 'nix log /nix/store/gjd7kvv35iypazl7z3vk4a7f3ib2wspj-cosmic-launcher-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/yw5xkaw5mdrhd4jm52yzqy8gv4h3dfwh-cosmic-launcher-0.1.0.drv' failed to build
```

Am I doing sth wrong?

**Comment by Mastermindaxe** [comment]
You're completely right! I guess I was just taken aback by the fact, that the flake doesn't build currently :smile: I just ran `nix flake update` and that fixed it :+1: Do you accept a PR for this?

**Comment by Elias-Graf** [comment]
@Mastermindaxe have you ever figured out how to actually run the modified version on nixos?

**Comment by Mastermindaxe** [comment]
Don't think I did tbh 🤔 @Elias-Graf 

But it was also quite some time ago so I might be misremembering...

**Comment by Elias-Graf** [comment]
@mmstick Sorry for tagging you here, but the repo doesn't seem to have discussions enabled. I would like to help and contribute some bug fixes, but the lack of extensive documentation (biggest offender being `cosmic-comp` itself) is a little bit of an obstacle. I can run the launcher using `nix run`, or `cargo run`, but it only seems to open an existing instance without the modifications. Maybe because the app is started in a way, it's supposed to be reused? And I can't really do the `just install`, since NixOs doesn't allow for that, and to be honest, would be cool if I didn't have to modify my system binaries to test this program.
But I might very well be mistaken, and was just running something the wrong way, or failed to save the file ^^ Still, would be great hearing from you, if you have the time, and giving a little pointer what the way to go is :)

PS: I've tried changing `run_single_instance` to just `run`, and also enabled `exit_on_close`, but that didn't seem to launch anything anymore.
